services:
#    czesio_nestable_page.example:
#        class: Czesio\NestablePageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    czesio_nestable_page.init:
        class: Czesio\NestablePageBundle\EventListener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}